Update maven agent to 3.6
openshift/jenkins pull request #1222
Opened 2021-02-09 12:11 UTC by waveywaves

2021-02-09 12:16 UTC, waveywaves commented
/bugzilla refresh

2021-02-09 12:17 UTC, waveywaves commented
/bugzilla refresh

2021-02-09 12:58 UTC, jkhelil commented
/lgtm

2021-02-10 20:48 UTC, bparees commented
@waveywaves 
1) this appears to be an RFE (per the linked bug), we don't generally backport features to z-streams, especially not 4.5 which is in maintenance support only.

2) seems odd you've changed the content w/o renaming the "maven-3.5" directories.

2021-02-11 11:59 UTC, siamaksade commented
@bparees Maven 3.5 is EOL which leaves 4.5 with no supported Maven agents for Jenkins. Therefore we aimed to backport to 4.5 as well, despite being in maintenance mode.

2021-02-11 15:11 UTC, bparees commented
not renaming the directories still seems like an odd choice but i don't want to hold you up from landing this, so i'm approving.

2021-02-11 15:17 UTC, siamaksade commented
@bparees agree about the directories

@waveywaves any reason for not adding a new directory for maven-3.6?

2021-02-11 16:32 UTC, akram commented
@siamaksade the initial fix has been done by a new comer on the project, and it has been LGTMed too quickly while I was not here.
for 3.11 , I have created a different directory, so, we should align. However, 4.x directory should be name `agent-maven`  to reflect the final image name which is version agnostic.

To complete the renaming, a PR within https://github.com/openshift/ocp-build-data/blob/openshift-4.5/images/jenkins-agent-maven-35-rhel7.yml should be done and that also may have impacts on ART build process.

2021-02-11 16:47 UTC, akram commented
one of the test pipeline is failing with the following error
```
First time build. Skipping changelog.
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build WAR)
[Pipeline] sh
+ mvn clean package -Popenshift
/tmp/workspace/e2e-test-jenkins-pipeline-7b6mc/e2e-test-jenkins-pipeline-7b6mc-openshift-jee-sample@tmp/durable-0ed0f482/script.sh: line 1: mvn: command not found
[Pipeline] }
[Pipeline] // stage
```

2021-02-11 16:49 UTC, bparees commented
/hold

2021-02-11 16:55 UTC, akram requested changes

2021-02-11 16:55 UTC, akram commented on agent-maven-3.5/Dockerfile.localdev
> +    PATH="${M2_HOME}/bin:${PATH}"
`\` are missing at the end of the lines.
The directory containg `mvn` must be added to PATH. It is if we take it from community.
see here https://github.com/openshift/jenkins/pull/1213/files#diff-6fa4f3817d9f36f09234c2a759b521340bd27d92c3f4a56e172330482f5574a3R10

The e2e test uses the community build for testing.

2021-03-04 05:21 UTC, waveywaves commented
/retest

2021-03-26 06:02 UTC, waveywaves commented
/retet

2021-03-26 06:08 UTC, waveywaves commented
/retest

2021-04-06 08:19 UTC, akram commented
/close

2021-04-06 08:19 UTC, akram commented
/reopen

2021-04-06 08:19 UTC, closed without merging

2021-04-06 10:35 UTC, waveywaves commented
/reopen