Bug 1974338: Update README.md with USE_JAVA_VERSION env var explanation
openshift/jenkins pull request #1307
Opened 2021-07-13 13:31 UTC by waveywaves

`USE_JAVA_VERSION` env var allows the user to set the java version of the jnlp client running in the jenkins agent image.

2021-07-13 13:54 UTC, adambkaplan requested changes

2021-07-13 13:54 UTC, adambkaplan commented on README.md
> +| `USE_JAVA_VERSION`	|	Allows you to set the Java version used by the JNLP Client for the agent images. By default the value is set to `java-11`	|
What are the allowed values? What value should a developer provide to use Java 8?

2021-07-13 13:56 UTC, gabemontero commented
/retitle Bug: 1974338: Update README.md with USE_JAVA_VERSION env var explanation

2021-07-13 14:37 UTC, gabemontero commented
/retitle Bug 1974338: Update README.md with USE_JAVA_VERSION env var explanation

2021-07-22 12:56 UTC, gabemontero commented
/lgtm

@rolfedh - we'll want to update the product docs for this as well.  Can we drive that off of this BZ, where @waveywaves perhaps crafts an openshift/openshift-docs PR for you?

Or do you prefer some other form or bookkeeping  / execution?

2021-07-22 12:57 UTC, gabemontero commented
Also @rolfedh of course if you have opinions on the specific wording from @waveywaves let us know.

2021-07-22 14:32 UTC, merged

2021-07-23 11:18 UTC, rolfedh commented
> /lgtm
> 
> @rolfedh - we'll want to update the product docs for this as well. Can we drive that off of this BZ, where @waveywaves perhaps crafts an openshift/openshift-docs PR for you?
> 
> Or do you prefer some other form or bookkeeping / execution?

Hi @gabemontero. I've created https://issues.redhat.com/browse/RHDEVDOCS-3177 to track the doc work for this Jenkins task. @Preeticp Here's another Jenkins-related doc task we need to consider for our planning.