Bug 2044951: Jenkins Fixes for CVE-2022-20618 CVE-2022-20619 - bump openshift-login to 1.0.27
openshift/jenkins pull request #1376
Opened 2022-01-28 00:45 UTC by gabemontero

/assign @akram 
/assign @adambkaplan

2022-01-28 02:50 UTC, gabemontero commented
/test e2e-aws

2022-01-28 14:04 UTC, adambkaplan commented
/hold

There are 4 other plugins which need to be updated as well.

2022-01-28 14:23 UTC, gabemontero commented
> /hold
> 
> There are 4 other plugins which need to be updated as well.

I think I have those updates now @adambkaplan 

See if the delta list I came up with from https://www.jenkins.io/security/advisory/2022-01-12/#SECURITY-2467 and https://www.jenkins.io/security/advisory/2022-01-12/#SECURITY-2033 lines up with your understanding

2022-01-28 14:45 UTC, gabemontero commented on 2/contrib/openshift/base-plugins.txt
> +mailer:408.vd726a_1130320
I am curious if the core jenkins bump pulls in this plugin version anyway @adambkaplan , given this is a "special case core plugin"

Assuming this is the one of the 4 items you are referring to, I may take a stab pre-merge of removing this line and see if the correct version is pulled in anyway.

Generally, the less number of plugins we cite/pin in this file, the better.

2022-01-28 15:08 UTC, gabemontero commented on 2/contrib/openshift/base-plugins.txt
> +mailer:408.vd726a_1130320
@adambkaplan and I talked in team meeting.  We'll save this experiment for a separate PR.

2022-01-28 16:17 UTC, gabemontero commented
based on the installed plugin list from there and the other PRs where you just posted the list, I believe there are more than 4 other plugins needed for https://www.jenkins.io/security/advisory/2022-01-12/#SECURITY-2033

PTAL

2022-01-28 16:34 UTC, gabemontero commented
> based on the installed plugin list from there and the other PRs where you just posted the list, I believe there are more than 4 other plugins needed for https://www.jenkins.io/security/advisory/2022-01-12/#SECURITY-2033
> 
> PTAL

@adambkaplan ^^

2022-01-28 16:34 UTC, gabemontero commented
/hold cancel

2022-01-28 16:42 UTC, adambkaplan requested changes
Can we check if we can drop an explicit dependency on mailer?

2022-01-28 16:42 UTC, adambkaplan commented on 2/contrib/openshift/base-plugins.txt
> +cloudbees-bitbucket-branch-source:746.v350d2781c184
This is the right call here. This plugin is a transitive dep of `blueocean` - they haven't cut a release that updates their dependency. I don't think there is a major risk that this breaks blueocean.

2022-01-28 16:47 UTC, gabemontero commented
I was being safer than sorry wrt https://github.com/openshift/jenkins/pull/1376#discussion_r794666780 but at this point we are not going to make code freeze anyway.

I'll remove (we need to retest anyway) and we'll see what the installed plugins looks like

2022-01-28 17:32 UTC, gabemontero commented
as we missed code freeze, it is conceivable https://bugzilla.redhat.com/show_bug.cgi?id=2047839 will have to be retargetted to 4.11 and we cherrypick back to 4.10.z, but we'll sort that out as the day progresses

2022-01-28 18:14 UTC, gabemontero commented
mailer plugin is at the appropriate level noted in the CVE @adambkaplan with the login plugin dep:

2022-01-28T16:55:11.456913647Z Installed plugins:
2022-01-28T16:55:11.462887985Z ace-editor:1.1
2022-01-28T16:55:11.468217478Z ant:1.11
2022-01-28T16:55:11.473623143Z apache-httpcomponents-client-4-api:4.5.13-1.0
2022-01-28T16:55:11.478968905Z authentication-tokens:1.4
2022-01-28T16:55:11.484339471Z blueocean-autofavorite:1.2.4
2022-01-28T16:55:11.489733115Z blueocean-bitbucket-pipeline:1.24.8
2022-01-28T16:55:11.495146051Z blueocean-commons:1.24.8
2022-01-28T16:55:11.500513333Z blueocean-config:1.24.8
2022-01-28T16:55:11.506199926Z blueocean-core-js:1.24.8
2022-01-28T16:55:11.511696614Z blueocean-dashboard:1.24.8
2022-01-28T16:55:11.517128209Z blueocean-display-url:2.4.1
2022-01-28T16:55:11.522591422Z blueocean-events:1.24.8
2022-01-28T16:55:11.527901417Z blueocean-github-pipeline:1.24.8
2022-01-28T16:55:11.533257023Z blueocean-git-pipeline:1.24.8
2022-01-28T16:55:11.538652523Z blueocean-i18n:1.24.8
2022-01-28T16:55:11.543938626Z blueocean:1.24.8
2022-01-28T16:55:11.549289309Z blueocean-jwt:1.24.8
2022-01-28T16:55:11.554567490Z blueocean-personalization:1.24.8
2022-01-28T16:55:11.559832785Z blueocean-pipeline-api-impl:1.24.8
2022-01-28T16:55:11.565114275Z blueocean-pipeline-editor:1.24.8
2022-01-28T16:55:11.570366392Z blueocean-pipeline-scm-api:1.24.8
2022-01-28T16:55:11.575644679Z blueocean-rest-impl:1.24.8
2022-01-28T16:55:11.580978125Z blueocean-rest:1.24.8
2022-01-28T16:55:11.586296697Z blueocean-web:1.24.8
2022-01-28T16:55:11.591631281Z bootstrap4-api:4.6.0-3
2022-01-28T16:55:11.596882350Z bouncycastle-api:2.25
2022-01-28T16:55:11.602163310Z branch-api:2.6.4
2022-01-28T16:55:11.607683666Z caffeine-api:2.9.2-29.v717aac953ff3
2022-01-28T16:55:11.613141181Z checks-api:1.7.2
2022-01-28T16:55:11.618505129Z cloudbees-bitbucket-branch-source:746.v350d2781c184
2022-01-28T16:55:11.623798462Z cloudbees-folder:6.16
2022-01-28T16:55:11.629148901Z config-file-provider:3.8.1
2022-01-28T16:55:11.634589829Z configuration-as-code-groovy:1.1
2022-01-28T16:55:11.639913612Z configuration-as-code:1.55.1
2022-01-28T16:55:11.645231303Z credentials-binding:1.27.1
2022-01-28T16:55:11.650616430Z credentials:2.6.1
2022-01-28T16:55:11.655895970Z display-url-api:2.3.5
2022-01-28T16:55:11.661155989Z docker-commons:1.18
2022-01-28T16:55:11.666367121Z durable-task:493.v195aefbb0ff2
2022-01-28T16:55:11.671596350Z echarts-api:5.0.2-1
2022-01-28T16:55:11.676825922Z favorite:2.3.1
2022-01-28T16:55:11.682218161Z font-awesome-api:5.15.2-2
2022-01-28T16:55:11.690387712Z git-client:3.9.0
2022-01-28T16:55:11.695644417Z github-api:1.114.2
2022-01-28T16:55:11.700920750Z github-branch-source:2.6.0
2022-01-28T16:55:11.706325249Z github:1.34.0
2022-01-28T16:55:11.711753693Z git:4.10.1
2022-01-28T16:55:11.717274170Z git-server:1.9
2022-01-28T16:55:11.722609788Z google-oauth-plugin:1.0.6
2022-01-28T16:55:11.727950668Z groovy:2.4
2022-01-28T16:55:11.733261415Z handy-uri-templates-2-api:2.1.8-1.0
2022-01-28T16:55:11.738534994Z htmlpublisher:1.25
2022-01-28T16:55:11.743885940Z jackson2-api:2.13.1-242.v1a45bad25ceb
2022-01-28T16:55:11.749119482Z javax-activation-api:1.2.0-2
2022-01-28T16:55:11.754439036Z javax-mail-api:1.6.2-2
2022-01-28T16:55:11.759738817Z jenkins-design-language:1.24.8
2022-01-28T16:55:11.765061154Z jira:3.5
2022-01-28T16:55:11.770465453Z job-dsl:1.77
2022-01-28T16:55:11.775799491Z jquery3-api:3.6.0-1
2022-01-28T16:55:11.781075199Z jsch:0.1.55.2
2022-01-28T16:55:11.786261731Z junit:1.52
2022-01-28T16:55:11.791538875Z kubernetes-client-api:5.10.1-171.vaa0774fb8c20
2022-01-28T16:55:11.796867345Z kubernetes-credentials:0.9.0
2022-01-28T16:55:11.802147032Z kubernetes:1.31.0
2022-01-28T16:55:11.807556360Z lockable-resources:2.11
2022-01-28T16:55:11.812960533Z mailer:408.vd726a_1130320
2022-01-28T16:55:11.818256626Z mapdb-api:1.0.9.0
2022-01-28T16:55:11.823505391Z matrix-auth:2.6.8
2022-01-28T16:55:11.828738593Z matrix-project:1.20
2022-01-28T16:55:11.834031268Z mercurial:2.15
2022-01-28T16:55:11.839323316Z metrics:4.0.2.8.1
2022-01-28T16:55:11.844525412Z oauth-credentials:0.4
2022-01-28T16:55:11.849878828Z okhttp-api:3.12.12.2
2022-01-28T16:55:11.855129874Z openshift-client:1.0.35
2022-01-28T16:55:11.860292885Z openshift-login:1.0.27
2022-01-28T16:55:11.865594420Z openshift-sync:1.0.53
2022-01-28T16:55:11.870885501Z pam-auth:1.6
2022-01-28T16:55:11.876084792Z pipeline-build-step:2.14
2022-01-28T16:55:11.881268434Z pipeline-graph-analysis:1.10
2022-01-28T16:55:11.886523444Z pipeline-input-step:2.12
2022-01-28T16:55:11.891812081Z pipeline-milestone-step:1.3.1
2022-01-28T16:55:11.897113068Z pipeline-model-api:1.9.3
2022-01-28T16:55:11.902360358Z pipeline-model-definition:1.8.4
2022-01-28T16:55:11.907803021Z pipeline-model-extensions:1.9.3
2022-01-28T16:55:11.913060179Z pipeline-rest-api:2.15
2022-01-28T16:55:11.918394638Z pipeline-stage-step:2.5
2022-01-28T16:55:11.923595099Z pipeline-stage-tags-metadata:1.8.4
2022-01-28T16:55:11.928865172Z plain-credentials:1.7
2022-01-28T16:55:11.934114212Z plugin-util-api:2.4.0
2022-01-28T16:55:11.939311717Z popper-api:1.16.1-2
2022-01-28T16:55:11.944565228Z prometheus:2.0.10
2022-01-28T16:55:11.949771264Z pubsub-light:1.13
2022-01-28T16:55:11.954928361Z scm-api:2.6.5
2022-01-28T16:55:11.960106695Z script-security:1.78
2022-01-28T16:55:11.965245647Z snakeyaml-api:1.29.1
2022-01-28T16:55:11.970478948Z sse-gateway:1.24
2022-01-28T16:55:11.975621756Z ssh-credentials:1.19
2022-01-28T16:55:11.980787004Z structs:308.v852b473a2b8c
2022-01-28T16:55:11.985960055Z subversion:2.15.1
2022-01-28T16:55:11.991124725Z token-macro:266.v44a80cf277fd
2022-01-28T16:55:11.996312538Z trilead-api:1.0.13
2022-01-28T16:55:12.001527162Z variant:1.4
2022-01-28T16:55:12.006744158Z workflow-api:2.47
2022-01-28T16:55:12.012452124Z workflow-basic-steps:2.20
2022-01-28T16:55:12.017773681Z workflow-cps-global-lib:2.17
2022-01-28T16:55:12.023051879Z workflow-cps:2.94
2022-01-28T16:55:12.028251147Z workflow-durable-task-step:2.35
2022-01-28T16:55:12.033514867Z workflow-job:2.41
2022-01-28T16:55:12.038684769Z workflow-multibranch:2.26
2022-01-28T16:55:12.043948359Z workflow-scm-step:2.13
2022-01-28T16:55:12.049221350Z workflow-step-api:2.24
2022-01-28T16:55:12.054503739Z workflow-support:3.8

2022-01-28 18:17 UTC, gabemontero commented
all the other plugins noted in the Fix  section in https://www.jenkins.io/security/advisory/2022-01-12/#SECURITY-2033 look good too @adambkaplan

2022-01-28 18:20 UTC, adambkaplan commented
/hold

We are now officially past the code freeze cutoff. Since this isn't a release blocker, I'm going to hold off on merging this until the dust settles and 4.11 opens.

2022-01-28 18:21 UTC, gabemontero commented
That said, the jenkins-client-plugin failure at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_jenkins/1376/pull-ci-openshift-jenkins-master-e2e-aws-jenkins-client-plugin/1487105615208648704 is in the test

but it is the very first build instantiation timing out .... very weird looking

very well may be  a CI infra flake, perhaps related to code freeze / master switch as we've noted here today ^^

will try again once things are officially transferred over

2022-01-28 20:23 UTC, adambkaplan commented
/retest

2022-01-29 01:49 UTC, gabemontero commented
/retest

2022-01-29 15:41 UTC, gabemontero commented
I think this plugin combination is resulting in an unhealthy jenkins.

I'll provision a cluster from this PR on Monday via clusterbot and investigate.

2022-01-31 15:59 UTC, gabemontero commented
Yep a bunch of plugin dependency pain .... will craft an updated plugin version declaration shortly.

```
2022-01-31 15:53:38 SEVERE  jenkins.InitReactorRunner$1 onTaskFailed Failed Loading plugin Git plugin v4.10.1 (git)
java.io.IOException: Failed to load: Git plugin (4.10.1)
 - Update required: Token Macro Plugin (266.v44a80cf277fd) to be updated to 267.vcdaea6462991 or higher
 - Update required: Jenkins Git client plugin (3.9.0) to be updated to 3.10.0 or higher
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-01-31 15:53:38 SEVERE  jenkins.InitReactorRunner$1 onTaskFailed Failed Loading plugin Autofavorite for Blue Ocean v1.2.4 (blueocean-autofavorite)
java.io.IOException: Failed to load: Autofavorite for Blue Ocean (1.2.4)
 - Failed to load: Git plugin (4.10.1)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-01-31 15:53:38 SEVERE  jenkins.InitReactorRunner$1 onTaskFailed Failed Loading plugin GitHub plugin v1.34.0 (github)
java.io.IOException: Failed to load: GitHub plugin (1.34.0)
 - Failed to load: Git plugin (4.10.1)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-01-31 15:53:38 SEVERE  jenkins.InitReactorRunner$1 onTaskFailed Failed Loading plugin GitHub Branch Source Plugin v2.6.0 (github-branch-source)
java.io.IOException: Failed to load: GitHub Branch Source Plugin (2.6.0)
 - Failed to load: GitHub plugin (1.34.0)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-01-31 15:53:38 SEVERE  jenkins.InitReactorRunner$1 onTaskFailed Failed Loading plugin Pipeline implementation for Blue Ocean v1.24.8 (blueocean-pipeline-api-impl)
java.io.IOException: Failed to load: Pipeline implementation for Blue Ocean (1.24.8)
 - Failed to load: Git plugin (4.10.1)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-01-31 15:53:38 SEVERE  jenkins.InitReactorRunner$1 onTaskFailed Failed Loading plugin Bitbucket Branch Source Plugin v746.v350d2781c184 (cloudbees-bitbucket-branch-source)
java.io.IOException: Failed to load: Bitbucket Branch Source Plugin (746.v350d2781c184)
 - Failed to load: Git plugin (4.10.1)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-01-31 15:53:38 SEVERE  jenkins.InitReactorRunner$1 onTaskFailed Failed Loading plugin Bitbucket Pipeline for Blue Ocean v1.24.8 (blueocean-bitbucket-pipeline)
java.io.IOException: Failed to load: Bitbucket Pipeline for Blue Ocean (1.24.8)
 - Failed to load: Pipeline implementation for Blue Ocean (1.24.8)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-01-31 15:53:38 SEVERE  jenkins.InitReactorRunner$1 onTaskFailed Failed Loading plugin Events API for Blue Ocean v1.24.8 (blueocean-events)
java.io.IOException: Failed to load: Events API for Blue Ocean (1.24.8)
 - Failed to load: Pipeline implementation for Blue Ocean (1.24.8 [...]

2022-01-31 16:28 UTC, gabemontero commented
ok made the necessary update (bumps to things we were already bumping) for ^^, then built locally /verified against my clusterbot cluster

2022-01-31 16:28 UTC, gabemontero commented
/hold cancel

2022-01-31 18:51 UTC, gabemontero commented
aws fail on client plugin

sync plugin pass good sign == not plugin dependency problems

/retest

2022-01-31 18:52 UTC, gabemontero commented
```
2022-01-31T16:35:22.309664971Z Installed plugins:
2022-01-31T16:35:22.332903849Z ace-editor:1.1
2022-01-31T16:35:22.351295040Z ant:1.11
2022-01-31T16:35:22.368204477Z apache-httpcomponents-client-4-api:4.5.13-1.0
2022-01-31T16:35:22.396368148Z authentication-tokens:1.4
2022-01-31T16:35:22.423734059Z blueocean-autofavorite:1.2.4
2022-01-31T16:35:22.452565842Z blueocean-bitbucket-pipeline:1.24.8
2022-01-31T16:35:22.466568418Z blueocean-commons:1.24.8
2022-01-31T16:35:22.469641404Z blueocean-config:1.24.8
2022-01-31T16:35:22.480498532Z blueocean-core-js:1.24.8
2022-01-31T16:35:22.490009486Z blueocean-dashboard:1.24.8
2022-01-31T16:35:22.510936995Z blueocean-display-url:2.4.1
2022-01-31T16:35:22.523547239Z blueocean-events:1.24.8
2022-01-31T16:35:22.532021603Z blueocean-github-pipeline:1.24.8
2022-01-31T16:35:22.586494964Z blueocean-git-pipeline:1.24.8
2022-01-31T16:35:22.602081589Z blueocean-i18n:1.24.8
2022-01-31T16:35:22.628864781Z blueocean:1.24.8
2022-01-31T16:35:22.661425855Z blueocean-jwt:1.24.8
2022-01-31T16:35:22.680455611Z blueocean-personalization:1.24.8
2022-01-31T16:35:22.694302266Z blueocean-pipeline-api-impl:1.24.8
2022-01-31T16:35:22.706735309Z blueocean-pipeline-editor:1.24.8
2022-01-31T16:35:22.727234865Z blueocean-pipeline-scm-api:1.24.8
2022-01-31T16:35:22.745230166Z blueocean-rest-impl:1.24.8
2022-01-31T16:35:22.777094423Z blueocean-rest:1.24.8
2022-01-31T16:35:22.819267486Z blueocean-web:1.24.8
2022-01-31T16:35:22.845082962Z bootstrap4-api:4.6.0-3
2022-01-31T16:35:22.860688801Z bouncycastle-api:2.25
2022-01-31T16:35:22.887138738Z branch-api:2.6.4
2022-01-31T16:35:22.907413082Z caffeine-api:2.9.2-29.v717aac953ff3
2022-01-31T16:35:22.925207991Z checks-api:1.7.2
2022-01-31T16:35:22.953276813Z cloudbees-bitbucket-branch-source:746.v350d2781c184
2022-01-31T16:35:22.984433500Z cloudbees-folder:6.16
2022-01-31T16:35:23.003144125Z config-file-provider:3.8.1
2022-01-31T16:35:23.009455770Z configuration-as-code-groovy:1.1
2022-01-31T16:35:23.028059143Z configuration-as-code:1.55.1
2022-01-31T16:35:23.047863860Z credentials-binding:1.27.1
2022-01-31T16:35:23.059198465Z credentials:2.6.1
2022-01-31T16:35:23.080247325Z display-url-api:2.3.5
2022-01-31T16:35:23.102453640Z docker-commons:1.18
2022-01-31T16:35:23.128939751Z durable-task:493.v195aefbb0ff2
2022-01-31T16:35:23.164379545Z echarts-api:5.0.2-1
2022-01-31T16:35:23.218524063Z favorite:2.3.1
2022-01-31T16:35:23.241129806Z font-awesome-api:5.15.2-2
2022-01-31T16:35:23.268268311Z git-client:3.10.0
2022-01-31T16:35:23.296515018Z github-api:1.114.2
2022-01-31T16:35:23.437153489Z github-branch-source:2.6.0
2022-01-31T16:35:23.466905080Z github:1.34.0
2022-01-31T16:35:23.494506749Z git:4.10.1
2022-01-31T16:35:23.523183925Z git-server:1.9
2022-01-31T16:35:23.561236034Z google-oauth-plugin:1.0.6
2022-01-31T16:35:23.593527352Z groovy:2.4
2022-01-31T16:35:23.646781052Z handy-uri-templates-2-api:2.1.8-1.0
2022-01-31T16:35:23.678294790Z htmlpublisher:1.25
2022-01-31T16:35:23.716882148Z jackson2-api:2.13.1-242.v1a45bad25ceb
2022-01-31T16:35:23.771291328Z javax-activation-api:1.2.0-2
2022-01-31T16:35:23.804523247Z javax-mail-api:1.6.2-2
2022-01-31T16:35:23.840263932Z jenkins-design-language:1.24.8
2022-01-31T16:35:23.851699519Z jira:3.5
2022-01-31T16:35:23.858012552Z job-dsl:1.77
2022-01-31T16:35:23.866262053Z jquery3-api:3.6.0-1
2022-01-31T16:35:23.882154824Z jsch:0.1.55.2
2022-01-31T16:35:23.912743240Z junit:1.52
2022-01-31T16:35:23.941585397Z kubernetes-client-api:5.10.1-171.vaa0774fb8c20
2022-01-31T16:35:23.959837284Z kubernetes-credentials:0.9.0
2022-01-31T16:35:24.000974829Z kubernetes:1.31.0
2022-01-31T16:35:24.030992849Z lockable-resources:2.11
2022-01-31T16:35:24.054221778Z mailer:408.vd726a_1130320
2022-01-31T16:35:24.080324447Z mapdb-api:1.0.9.0
2022-01-31T16:35:24.108389120Z matrix-auth:2.6.8
2022-01-31T16:35:24.170438399Z matrix-project:1.20
2022-01-31T16:35:24.196846636Z mercurial:2.15
2022-01-31T16:35:24.227930358Z metrics:4.0.2.8.1
2022-01-31T16:35:24.247719164Z oauth-credentials:0.4
2022-01-31T16:35:24.273644198Z okhttp-api:3.12.12.2
2022-01-31T16:35:24.292026712Z openshift-client:1.0.35
2022-01-31T16:35:24.331388153Z openshift-login:1.0.27
2022-01-31T16:35:24.366941867Z openshift-sync:1.0.53
2022-01-31T16:35:24.394471615Z pam-auth:1.6
2022-01-31T16:35:24.422302821Z pipeline-build-step:2.14
2022-01-31T16:35:24.464000167Z pipeline-graph-analysis:1.10
2022-01-31T16:35:24.491571155Z pipeline-input-step:2.12
2022-01-31T16:35:24.510463220Z pipeline-milestone-step:1.3.1
2022-01-31T16:35:24.602529807Z pipeline-model-api:1.9.3
2022-01-31T16:35:24.651523631Z pipeline-model-definition:1.8.4
2022-01-31T16:35:24.700542319Z pipeline-model-extensions:1.9.3
2022-01-31T16:35:24.728502404Z pipeline-rest-api:2.15
2022-01-31T16:35:24.754294199Z pipeline-stage-step:2.5
2022-01-31T16:35:24.777489711Z pipeline-stage-tags-metadata:1.8.4
2022-01-31T16:35:24.811957240Z plain-credentials:1.7
2022-01-31T16:35:24.866061605Z plugin-util-api:2.4.0
2022-01-31T16:35:24.874808585Z popper-api:1.16.1-2
2022-01-31T16:35:24.890184550Z prometheus:2.0.10
2022-01-31T16:35:24.935387239Z pubsub-light:1.13
2022-01-31T16:35:24.973107471Z scm-api:2.6.5
2022-01-31T16:35:25.006656317Z script-security:1.78
2022-01-31T16:35:25.066424040Z snakeyaml-api:1.29.1
2022-01-31T16:35:25.089428492Z sse-gateway:1.24
2022-01-31T16:35:25.121480215Z ssh-credentials:1.19
2022-01-31T16:35:25.159660674Z structs:308.v852b473a2b8c
2022-01-31T16:35:25.184399475Z subversion:2.15.1
2022-01-31T16:35:25.201708547Z token-macro:267.vcdaea6462991
2022-01-31T16:35:25.232508653Z trilead-api:1.0.13
2022-01-31T16:35:25.257937372Z variant:1.4
2022-01-31T16:35:25.297450886Z workflow-api:2.47
2022-01-31T16:35:25.309254502Z workflow-basic-steps:2.20
2022-01-31T16:35:25.328390434Z workflow-cps-global-lib:2.17
2022-01-31T16:35:25.371700415Z workflow-cps:2.94
2022-01-31T16:35:25.382416679Z workflow-durable-task-step:2.35
2022-01-31T16:35:25.395781859Z workflow-job:2.41
2022-01-31T16:35:25.412248954Z workflow-multibranch:2.26
2022-01-31T16:35:25.436601445Z workflow-scm-step:2.13
2022-01-31T16:35:25.470426799Z workflow-step-api:2.24
2022-01-31T16:35:25.494813616Z workflow-support:3.8
```

2022-01-31 20:23 UTC, gabemontero commented
bump @adambkaplan @akram 

if we are all good with the plugin bumps, tag for merge and I'll commission the ART request

2022-01-31 22:09 UTC, adambkaplan commented
/hold

@akram do we want to land #1374 first?

2022-01-31 22:09 UTC, adambkaplan approved these changes
/lgtm

2022-02-01 00:47 UTC, gabemontero commented
aws / install fail

/retest

2022-02-01 04:55 UTC, akram commented
@adambkaplan we can land them indifferently. #1374 is not impacted by this one.

2022-02-01 16:44 UTC, gabemontero commented
/hold cancel

2022-02-01 18:27 UTC, merged