steps definition for sidecar-pattern-jenkins feature
openshift/jenkins pull request #1383
Opened 2022-02-01 12:30 UTC by jitendar-singh

- updating the scenario in sidecar-pattern-jenkins.feature file
- defining the steps for the feature in steps.py
- updating openshift.py

2022-02-01 12:31 UTC, jitendar-singh commented
/assign @akram

2022-02-01 13:01 UTC, akram requested changes

2022-02-01 13:01 UTC, akram commented on smoke/features/steps/openshift.py
> +                    time.sleep(5)
this one also should be parametrizable

2022-02-01 13:01 UTC, akram commented on smoke/features/steps/steps.py
> +    time.sleep(75)
that's a long sleep time, we need something more flexible and able to fail faster in case of an error.

2022-02-01 13:09 UTC, jitendar-singh commented
/retest

2022-02-12 13:16 UTC, akram commented
/retest

2022-02-16 13:32 UTC, gabemontero commented
/label docs-approved 

QE only

2022-02-16 13:32 UTC, gabemontero commented
/label px-approved

QE only

2022-02-16 13:32 UTC, gabemontero commented
/label qe-approved

QE centric

2022-02-16 13:34 UTC, merged

2022-02-16 13:40 UTC, prietyc123 commented
/label qe-approved